# Course - Introduction to R 

##### NOTE: 
1. Your code MUST execute without any errors. 
2. You can add more lines in your code as required.

## Section 1: Data Types and Operations Pt. 1

### Question 1 
**Create the variables with the following composition:**
1. A vector containing each letter of your first name as its elements.
2. A variable that contains your name concatenated from the vector created in (1)
3. A variable containing a sequence from 100 to 120.
4. Create a matrix of 3x3 dimensions that contains the even sequence of numbers starting from 2.
5. Assign names to the variables.

In [1]:
#### Start solution ####

In [2]:
## 1. A vector containing each letter of your first name as its elements.

m <- c('z','o','h','a','i','b')  

In [3]:
print(m)

[1] "z" "o" "h" "a" "i" "b"


In [6]:
## 2. A variable that contains your name concatenated from the vector created in (1)

name = paste(m)

In [9]:
name

[1] "z" "o" "h" "a" "i" "b"

In [12]:
## 3. A variable containing a sequence from 100 to 120.

seq= 100:120   

In [13]:
seq

[1] 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118
[20] 119 120

In [14]:
## 4. Create a matrix of 3x3 dimensions that contains the even sequence of numbers starting from 2.

mat <- matrix(seq(2,18,by = 2),nrow = 3,ncol = 3) 

In [15]:
mat

[,1] [,2] [,3]
[1,] 2     8   14  
[2,] 4    10   16  
[3,] 6    12   18

In [16]:
## 5. Assign names to the variables.

Name_vector = m
Name_concat = name
sequence = seq
MATRIX = mat

Name_vector
Name_concat
sequence
MATRIX

[1] "z" "o" "h" "a" "i" "b"

[1] "z" "o" "h" "a" "i" "b"

[1] 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118
[20] 119 120

[,1] [,2] [,3]
[1,] 2     8   14  
[2,] 4    10   16  
[3,] 6    12   18

In [17]:
#### End solution ####

### Question 2
**Create a factor variable emp_status:**
1. Containing the categorical variables: Employed, Unemployed, Self-Employed, with each level appearing atleast more than 2.
2. Display the levels and the factor variable as a table.
3. Unclass the elements of the factor variable.

In [18]:
#### Start solution ####

In [19]:
## 1. Containing the categorical variables: Employed, Unemployed, Self-Employed, with each level appearing atleast more than 2.

emp_status <- factor(c("Unemployed","Employed","Employed","Self-Employed","Self-Employed","Unemployed","Employed"))

In [20]:
## 2. Display the levels and the factor variable as a table.

emp_status
levels(emp_status)
class(emp_status)

[1] Unemployed    Employed      Employed      Self-Employed Self-Employed
[6] Unemployed    Employed     
Levels: Employed Self-Employed Unemployed

[1] "Employed"      "Self-Employed" "Unemployed"

[1] "factor"

In [21]:
## 3.Unclass the elements of the factor variable.

unclass(emp_status)

[1] 3 1 1 2 2 3 1
attr(,"levels")
[1] "Employed"      "Self-Employed" "Unemployed"

In [22]:
#### End solution ####

### Question 3
**Create a dataframe object called bank_customers:**
1. the data frame will have three columns: CustomerID, hasAccount, totalBalance
2. Fill the data as follows
    a. Alicia does not have an account. She is here for inquiry 
    b. Nancy is here to check on her account balance of USD 10,000.
    c. Fernando is here to deposit USD 100 in his account which had no balance.
    d. Louis will withdraw all his money from the account that had USD 2,000. 
    e. Diane is here for information. 
3. For customers that do not have a value, use NA as placeholder.
4. Print the number of rows, columns and names for the data frame.

In [23]:
#### Start solution ####

In [24]:

bank_customers = data.frame(CustomerID=c("Alicia","Nancy","Fernando","Louis","Diane"),hasAccount=c(NA,"Yes","Yes","Yes",NA),
                                "totalBalance_USD"=c(NA,10000,100,2000,NA))

In [25]:
bank_customers

CustomerID hasAccount totalBalance_USD
1 Alicia     NA            NA           
2 Nancy      Yes        10000           
3 Fernando   Yes          100           
4 Louis      Yes         2000           
5 Diane      NA            NA

In [26]:
nrow(bank_customers)
ncol(bank_customers)
names(bank_customers)

[1] 5

[1] 3

[1] "CustomerID"       "hasAccount"       "totalBalance_USD"

In [27]:
#### End solution ####

### Good Job! You have successfully completed the section!

## Section 2: Control Structures 

### Question 1
**Create a variable containing a sequence of numbers from 1 to 100:**
1. Iterate over the variables and print those numbers which are prime.

**Create a variable var with a value of 1:**
1. Create a while loop and increase the value of var at each iteration. 
2. When you reach the 10th prime number, terminate the loop and print the number.

In [28]:
#### Start solution ####

In [69]:
prime_numbers <- function(n) {
if (n >= 2) {
 x = seq(2, n)
 prime_nums = c()
 for (i in seq(2, n)) {
 if (any(x == i)) {
 prime_nums = c(prime_nums, i)
 x = c(x[(x %% i) != 0], i)
 }
 }
 return(prime_nums)
 }
 else 
 {
 stop("Input number should be at least 2.")
 }
 } 

In [63]:
prime_numbers(100)

[1]  2  3  5  7 11 13 17 19 23 29 31 37 41 43 47 53 59 61 67 71 73 79 83 89 97

In [94]:
num=2
count=0
for(i in 1:num){
    if(num%%i==0){
      count<-count+1
    }
}

if(count==2){
    print(paste(num," is Prime"))
    }else{
        print(paste(num," is not Prime"))
    }


[1] "2  is Prime"


In [6]:
#### End solution ####

### Question 2
**Create a matrix of size 3x3 called mat_1:**
1. Iterate over all the values one by one and print the element as well as the position in the matrix (row, col)

In [9]:
#### Start solution ####

In [132]:
mat_1<-matrix(1:9,3,3)

In [133]:
mat_1

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

In [134]:
for(i in seq_len(nrow(mat_1))){
    for(j in seq_len(ncol(mat_1))){
       print(paste("Row ",i," and Column ",j," has value ",mat_1[i,j]))
              }
}

[1] "Row  1  and Column  1  has value  1"
[1] "Row  1  and Column  2  has value  4"
[1] "Row  1  and Column  3  has value  7"
[1] "Row  2  and Column  1  has value  2"
[1] "Row  2  and Column  2  has value  5"
[1] "Row  2  and Column  3  has value  8"
[1] "Row  3  and Column  1  has value  3"
[1] "Row  3  and Column  2  has value  6"
[1] "Row  3  and Column  3  has value  9"


In [14]:
#### End solution ####

### Good Job! You have successfully completed the section!

## Section 3: Functions

### Question 1
**Create a function called gcd that finds the greatest common divisor of two numbers a and b:**
1. a and b, should be taken as input.
2. The function must print the GCD as well as return it.
3. The output must be saved in a variable called answer.

In [9]:
#### Start solution ####

In [61]:
gcd <- function(a, b) {
# choose the smaller number
if(a > b) {
smaller = b
} else {
smaller = a
}
for(i in 1:smaller) {
if((a %% i == 0) && (b %% i == 0)) {
gcd = i
}
}
print(paste("The G.C.D of", a,"and", b,"is", gcd))
return(gcd)
}

In [62]:
# taking input from the user
num1 = as.integer(readline(prompt = "Enter first number: "))
num2 = as.integer(readline(prompt = "Enter second number: "))
answer=hcf(num1,num2)
print(paste("The G.C.D of", num1,"and", num2,"is", answer))

Enter first number: 100
Enter second number: 200
[1] "The H.C.F. of 100 and 200 is 100"
[1] "The G.C.D of 100 and 200 is 100"


In [14]:
#### End solution ####

### Question 2
**Create a function called allConditionsMeet, that checks whether two expressions evaluate to true:**
1. a and b, should be taken as input.
2. the function should check if a and b, both conditions, evaluate to True.
3. The function must returns a boolean value.
4. Using a method, print the arguments that function takes.

In [9]:
#### Start solution ####

In [96]:
allConditionsMeet <- function(a,b)
{
   #print(paste(a,b))
    if(a>=10 && b<=100){
         print(paste(a,b))
        return(TRUE)
    } else {
         print(paste(a,b))
        return(FALSE)
    }
}

In [97]:
allConditionsMeet(200,50)

[1] "200 50"


[1] TRUE

In [14]:
#### End solution ####

### Good Job! You have successfully completed the section!

## Section 4: Vectorized Operations

### Question 1
**Create two matrices matrix_1 and matrix_2 of dimensions 2x3 and 3x2:**
1. Perform element-wise multiplication.
2. Perform matrix multipilcation. 

**Create a 2x2 matrix my_mat:**
1. Write a function to find the determinant of the matrix.

In [9]:
#### Start solution ####

In [131]:
matrix_1<-matrix(1:6,2,3);  matrix_2<-matrix(7:12,3,2)

In [132]:
matrix_1
matrix_2

[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

[,1] [,2]
[1,] 7    10  
[2,] 8    11  
[3,] 9    12

In [138]:
# for element wise multiplication we have to take the transpose of anyone of the matrix
matrix_1_t=t(matrix_1)  ## Taking transpose of matrix_1
elemul=matrix_1_t*matrix_2  ## element wise mulitplication
matrixmultiply=matrix_1%*%matrix_2  ## matrix multiplication

In [139]:
elemul
matrixmultiply

[,1] [,2]
[1,]  7   20  
[2,] 24   44  
[3,] 45   72

[,1] [,2]
[1,]  76  103 
[2,] 100  136

In [127]:
det<-function(matrixx)    ### Calculating the determinant
    {
       det=matrixx[1,1]*matrixx[2,2] - matrixx[2,1]*matrixx[1,2]
       return(det)
        }

In [128]:
my_mat<-matrix(1:4,2,2)

In [129]:
my_mat

[,1] [,2]
[1,] 1    3   
[2,] 2    4

In [130]:
answer=det(my_mat)
print(paste("Determinant of given matrix is ", answer))

[1] "Determinant of given matrix is  -2"


In [14]:
#### End solution ####

### Good Job! You have successfully completed the section!

## Section 5: Date and Time in R

### Question 1
**Use the current date and time and store them into variables curr_date and curr_time respectively: [use sys]**
1. Convert both into date and time objects using the appropriate functions.
2. Print the weekday, year, second and hour using the appropriate function and variables.

In [9]:
#### Start solution ####

In [47]:
curr_date=Sys.Date()
curr_time=Sys.time()

In [48]:
curr_date
curr_time

[1] "2020-10-04"

[1] "2020-10-04 15:06:54 PKT"

In [49]:
class(curr_date)
class(curr_time)

[1] "Date"

[1] "POSIXct" "POSIXt"

In [50]:
d=as.POSIXlt(curr_time)   ### converting class to Pure POSIXlt to extract the desired values

In [51]:
class(d)   

[1] "POSIXlt" "POSIXt"

In [52]:
names(unclass(d))

[1] "sec"    "min"    "hour"   "mday"   "mon"    "year"   "wday"   "yday"  
 [9] "isdst"  "zone"   "gmtoff"

In [53]:
d$wday   ## 0 refers to Sunday
d$year   ## 120th year because R has its origin set at 1900-01-01
d$sec
d$hour

[1] 0

[1] 120

[1] 54.92667

[1] 15

In [14]:
#### End solution ####

### Question 2
**Create a variable to store current date/time**
1. Create another variable that stores and set the timezone as GMT-5
2. Find the difference between your current time and the GMT-5 timezone.

In [9]:
#### Start solution ####

In [169]:
c<-Sys.time()

In [170]:
c

[1] "2020-10-06 19:32:56 PKT"

In [175]:
a<-as.POSIXct("2020-10-06",tz = "GMt-5")

Warning message in strptime(xx, f, tz = tz):
"unknown timezone 'GMt-5'"Warning message in as.POSIXct.POSIXlt(x):
"unknown timezone 'GMt-5'"Warning message in strptime(xx, f, tz = tz):
"unknown timezone 'GMt-5'"Warning message in as.POSIXct.POSIXlt(x):
"unknown timezone 'GMt-5'"Warning message in strptime(xx, f, tz = tz):
"unknown timezone 'GMt-5'"Warning message in as.POSIXct.POSIXlt(x):
"unknown timezone 'GMt-5'"Warning message in strptime(xx, f, tz = tz):
"unknown timezone 'GMt-5'"Warning message in as.POSIXct.POSIXlt(x):
"unknown timezone 'GMt-5'"Warning message in strptime(xx, f, tz = tz):
"unknown timezone 'GMt-5'"Warning message in as.POSIXct.POSIXlt(x):
"unknown timezone 'GMt-5'"Warning message in strptime(x, f, tz = tz):
"unknown timezone 'GMt-5'"Warning message in as.POSIXct.POSIXlt(as.POSIXlt(x, tz, ...), tz, ...):
"unknown timezone 'GMt-5'"

In [176]:
c-a

Time difference of 19.54891 hours

In [14]:
#### End solution ####

### Good Job! You have successfully completed the section!

## Section 6: Loop Functions

### Question 1
**Create a function to calculate mean and standard deviation of the provided data**
1. Create a sequence of numbers from 100 to 150 store in a variable called numbers.
1. Use lapply, sapply, apply and tapply to implement the functions on "numbers" [only on the second half of the sequence for tapply]

In [9]:
#### Start solution ####

In [93]:
numbers=list(101:150)     ### creating a list for lapply and sapply operations
numbers1<-matrix(101:150,10,5)    ### creating a matrix for apply operations
t<-c(101:150)   ## created a vector for tapply operations
f<-gl(4,12.5)    ## created 4 chunks of 12.5 as a factors for tapply operations

In [94]:
lapply(numbers,mean)  ## caluclating mean using lapply for numbers list
lapply(numbers,sd)    ## caluclating sd using lapply for numbers list
sapply(numbers,mean)  ## caluclating mean using sapply for numbers list
sapply(numbers,sd)    ## caluclating sd using sapply for numbers list

[[1]]
[1] 125.5

[[1]]
[1] 14.57738

[1] 125.5

[1] 14.57738

In [95]:
apply(numbers1,1,mean)   ## caluclating mean using apply for numbers1 array for the 10 rows
apply(numbers1,2,sd)   ## caluclating sd using apply for numbers1 array for the 5 columns

[1] 121 122 123 124 125 126 127 128 129 130

[1] 3.02765 3.02765 3.02765 3.02765 3.02765

In [121]:
tapply(t,f,mean)
tapply(t,f,sd)

1        2        3        4 
112.6429 118.5000 130.5000 142.5000

1         2         3         4 
15.964418  3.605551  3.605551  3.605551

In [14]:
#### End solution ####

### Question 2
**Create a matrix of dimensions 4x4**
1. Find the row-wise and column-wise mean of the matrix.
2. Print the values.

In [9]:
#### Start solution ####

In [115]:
mat<-matrix(rnorm(16),4,4)

In [116]:
mat

[,1]        [,2]       [,3]       [,4]       
[1,] -1.25774513  0.9526132 -0.3555842 -0.06417302
[2,] -0.05291876 -2.0871745 -0.2662136 -0.46681608
[3,] -0.88405243 -0.9588882 -0.6936611 -0.07386543
[4,] -2.62941616 -1.2983690  0.1504856  0.76873127

In [117]:
apply(mat,1,mean)  ### Row wise mean
apply(mat,2,mean)   ### Column wise mean

[1] -0.1812223 -0.7182807 -0.6526168 -0.7521421

[1] -1.20603312 -0.84795461 -0.29124330  0.04096919

In [14]:
#### End solution ####

### Good Job! You have successfully completed the section!

## Section 7: Data Split

### Question 1
**Using the data frame Orange:**
1. Using split function to break down the dataset on circumference and store it in 'split_data' variable. 
2. Print the values for split_data where circumference is 30 and 75.
3. Find the average age of the tree when the circumference is 30 and when circumference is 214.


The dataset is loaded and the variable Orange contains the respective dataset.

In [147]:
library(datasets)

In [148]:
head(Orange)

Tree age  circumference
1 1     118  30          
2 1     484  58          
3 1     664  87          
4 1    1004 115          
5 1    1231 120          
6 1    1372 142

In [149]:
#### Start solution ####

In [150]:
split_data<-split(Orange,Orange$circumference)

In [159]:
split_data$'30'
split_data$'75'

Tree age circumference
1  1    118 30           
15 3    118 30           
29 5    118 30

Tree age circumference
17 3    664 75

In [168]:
x=split_data$'30'
y=split_data$'214'
x
y

Tree age circumference
1  1    118 30           
15 3    118 30           
29 5    118 30

Tree age  circumference
28 4    1582 214

In [165]:
mean(x$age)
mean(y$age)

[1] 118

[1] 1582

In [14]:
#### End solution ####


### Save it and push .ipynb and .html file to your Github Repository
## GOOD JOB! You have successfully finished the course!